import {
  LucideActivity,
  LucideArrowDown,
  LucideArrowUp,
  LucideArrowUpDown,
  LucideBox,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronUp,
  LucideChevronsDown,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideClock,
  LucideCopy,
  LucideDownload,
  LucideEraser,
  LucideFileText,
  LucideFunnel,
  LucideIcon,
  LucideInfo,
  LucideLayers,
  LucideMonitor,
  LucideMoon,
  LucidePause,
  LucidePlay,
  LucidePlus,
  LucideRefreshCw,
  LucideRotateCw,
  LucideScrollText,
  LucideSearch,
  LucideServer,
  LucideSettings,
  LucideSquare,
  LucideSun,
  LucideTerminal,
  LucideTextWrap,
  LucideTrash,
  LucideTriangleAlert,
  LucideX,
} from '@lucide/angular';

/** The icon set the app uses — keeps templates free of per-icon imports. */
export const ICONS = {
  activity: LucideActivity,
  alert: LucideCircleAlert,
  check: LucideCheck,
  'chevron-down': LucideChevronDown,
  'chevron-right': LucideChevronRight,
  'chevron-up': LucideChevronUp,
  clock: LucideClock,
  close: LucideX,
  copy: LucideCopy,
  doc: LucideFileText,
  download: LucideDownload,
  eraser: LucideEraser,
  filter: LucideFunnel,
  follow: LucideChevronsDown,
  info: LucideInfo,
  logs: LucideScrollText,
  monitor: LucideMonitor,
  moon: LucideMoon,
  ok: LucideCircleCheck,
  pause: LucidePause,
  play: LucidePlay,
  plus: LucidePlus,
  pods: LucideBox,
  refresh: LucideRefreshCw,
  rotate: LucideRotateCw,
  search: LucideSearch,
  server: LucideServer,
  settings: LucideSettings,
  sort: LucideArrowUpDown,
  'sort-asc': LucideArrowUp,
  'sort-desc': LucideArrowDown,
  stop: LucideSquare,
  sun: LucideSun,
  terminal: LucideTerminal,
  trash: LucideTrash,
  warning: LucideTriangleAlert,
  workloads: LucideLayers,
  wrap: LucideTextWrap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
